# Generated by Django 5.0.6 on 2024-06-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_assignment_status_alter_assignment_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[(0, 'On Progress'), (1, 'Completed')], default='onprogress', max_length=10),
        ),
    ]
