# Generated by Django 5.0.6 on 2024-06-19 16:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
