# Generated by Django 5.0.6 on 2024-06-20 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_studentreport_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.assignment'),
        ),
    ]
