# Generated by Django 5.0.6 on 2024-06-20 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_studentreport_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.submittedassignment'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='student',
            field=models.ForeignKey(limit_choices_to={'group': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
