# Generated by Django 5.0.6 on 2024-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('siswa', 'Siswa'), ('guru', 'Guru')], default='siswa', max_length=5),
        ),
    ]
