# Generated by Django 5.0.6 on 2024-07-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], default=100, max_length=1),
            preserve_default=False,
        ),
    ]
