"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@d963vhv%0@yi4$dfd5qp8h55x$zevqwcxqhwd7fv+hh8-#xfe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '.vercel.app']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'crispy_bootstrap4',
    'ckeditor',
    'ckeditor_uploader',
    'django_summernote',
    'classroom',
    'posts',
    'users',
    'openforms',
    'comments',
    'courses',
    'whiteboard',
    'assignments',
    'ide',
    'newsletter',
    'contactus',
    'crispy_forms',
    'sweetify'
]
SWEETIFY_SWEETALERT_LIBRARY = 'sweetalert2'
CELERY_BEAT_SCHEDULE = {
    'update-tugas-status-every-minute': {
        'task': 'posts.tasks.update_tugas_status',
        'schedule': 60.0,  # setiap 60 detik
    },
}
MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'posts.middleware.UpdateTugasStatusMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "core", "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

import pytz

# Pengaturan Zona Waktu
TIME_ZONE = 'Asia/Jakarta'
USE_TZ = True

USE_I18N = True

USE_L10N = True

USE_TZ = True

SUMMERNOTE_THEME = 'bs4'  # Show summernote with Bootstrap4
# SUMMERNOTE_CONFIG = {
#     'iframe': False,  # Set to True if you want Summernote to use an iframe
#     'summernote': {
#         'width': '100%',  # Set editor width
#         'height': '480',  # Set editor height
#         'toolbar': [
#             ['style', ['style']],
#             ['font', ['bold', 'italic', 'underline', 'clear']],
#             ['fontname', ['fontname']],
#             ['color', ['color']],
#             ['para', ['ul', 'ol', 'paragraph']],
#             ['height', ['height']],
#             ['table', ['table']],
#             ['insert', ['link', 'picture', 'video']],
#             ['view', ['fullscreen', 'codeview', 'help']],
#         ],
#     },
# }
SUMMERNOTE_CONFIG = {
    'toolbar': [
        ['style', ['bold', 'italic', 'underline', 'clear']],
        ['para', ['ul']],
    ],
    'summernote': {
        'width': '100%',
        'height': '300px',
    },
    'js': ('/static/js/summernote_footer.js',), 
    'css': ('/static/css/summernote_custom.css',), 
}


KEDITOR_FILENAME_GENERATOR = 'utils.get_filename'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
    },
}

X_FRAME_OPTIONS = 'SAMEORIGIN'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core/static'),
]

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'classroom:dashboard'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hatami391998@gmail.com'
EMAIL_HOST_PASSWORD = 'istimewajogja1234'

DEFAULT_AUTO_FIELD='django.db.models.AutoField' 